language: ruby
before_script:
- ln -s settings.yml.travis config/settings.yml
- bundle exec rake db:setup
script:
- bundle exec rspec spec
notifications:
  slack:
    secure: R7Ydqu5YZqZxsbxujfI4XmQ40ApzAD92RQYDdOH706t0PIixYCx3cjIZr0jAkUOFDVHA9303OLvXzHFl6ed7UQZ0JTydzd4TKPDm757GVAT6KzrZpffLc88dD/BVzQgfG8SVsXmNpGP//LNGeSHrD8iGR0dkxVQbR03Ud/5nMiOkccA9klwKGTwrDUuDeZNZeSjjQFAUgAsH77qNXj9YBbFBa+4Xc3biugv6C9DrnQ6LG+1rYPulfZvOR81AAedKpJt82f/tnIm97OJ+j6Bih9GB1pG3+U0wRn6PHQf5dh/BD9hninbOXnq7sdjmN2C8jtddmj5hO84k4wvZCNLNO6LF+PALHM2OroZ/8HRzdtS+1ATWauObFnslOmqdDtvbV6BXOKAOW5pm1u0fI5JXfAfaA/NXI3laNqa8pNAYbysTH54Jw9QccGQ4giiXKdiGL0RZ9ePXSlpXulrKHmwBOgdbxgXOrzczo2YIuUHFiPr9FaOyqQEXaWJI2xgEIuyWJ2eEdKDf86ztdxDf3An32anP7sX/iej1tj5cJUZA28Io8NDcz4/jWY2Ou/4HVTvnI4f7Nr42vtjxla352uest4jLbpr2nRA6mYkoCfVDusTGRS2pZY9GeD6zflOw4RaWGhebc1tq99AMLZoX/vjTwgSB19+gJvUJAB1fmez5KaI=
